In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import accuracy_score
from sklearn.neighbors import NearestCentroid

In [2]:
iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

y = df.pop("target").to_numpy()
X = df.to_numpy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, shuffle = True, random_state = 0)

In [3]:
model_sk = NearestCentroid()
model_sk.fit(X_train, y_train)
y_pred = model_sk.predict(X_test)
accuracy_score(y_test, y_pred)

0.9

In [4]:
class MyNearestCentroid:
    def fit(self, X, y):
        self.labels = np.unique(y)
        self.centroids = []
        for lbl in self.labels:
            y_lbl = y[y==lbl]
            X_lbl = X[y==lbl]
            centroid = np.mean(X_lbl, axis=0)
            self.centroids.append(centroid)

    """
        prediction with traditional nested loop
        This function has a sneaky bug that prevents it from working as expected.
        Identify & fix the bug & ping me your answers. This is first part of AML assignment 1
    """
    def predict(self, X):
      num_records = X.shape[0]
      y_pred_distances = np.empty((num_records, len(self.labels)))

      for i in np.arange(0, num_records):
        for j, centroid in enumerate(self.centroids.values()):  # Fix 1: Use self.centroids.values() to iterate through centroids
            y_pred_distances[i, j] = np.linalg.norm(X[i] - centroid)  # Fix 2: Remove [j] after centroid

      y_pred = np.argmin(y_pred_distances, axis=1)
      return y_pred


    """
        TODO: Add vectorized code to do prediction
        This is second part of AML assignment 1
    """
    def predict(self, X):
      num_records = X.shape[0]
      y_pred_distances = np.empty((num_records, len(self.labels)))

      for j, label in enumerate(self.labels):
        centroid = self.centroids[label]
        y_pred_distances[:, j] = np.linalg.norm(X - centroid, axis=1)

      y_pred = np.argmin(y_pred_distances, axis=1)
      return y_pred

In [ ]:
    #def predict(self, X):
        #num_records = X.shape[0]
        #y_pred_distances = np.empty((num_records, len(self.labels)))
        #for i in np.arange(0,num_records):
            #for j, centroid in enumerate(self.centroids):
                #y_pred_distances[i, j] = np.linalg.norm(X[i] - centroid[j], axis=0)

        #y_pred =  np.argmin(y_pred_distances, axis=1)
        #return y_pred


In [5]:
mymodel = MyNearestCentroid()
mymodel.fit(X_train, y_train)

print(mymodel.labels)
mymodel.centroids

[0 1 2]


[array([5.02051282, 3.4025641 , 1.46153846, 0.24102564]),
 array([5.88648649, 2.76216216, 4.21621622, 1.32432432]),
 array([6.63863636, 2.98863636, 5.56590909, 2.03181818])]

In [6]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [7]:
y_pred = mymodel.predict(X_test)
accuracy_score(y_test, y_pred)

0.9